### ISSUE TITLE
usage?

### ISSUE THREAD

**Issue by corysimmons** [UnderlineWords/Agola-Color-Schemes#1]
![image](https://cloud.githubusercontent.com/assets/224636/12908688/ab6c8972-cec7-11e5-90c1-70474b70b9fe.png)

it's installed

**Comment by UnderlineWords** [comment]
Please check your package root **`"Packages/User/SublimeLinter/"`**

You can add this line in Settings - User (Preferences.sublime-settings);
`"color_scheme": "Packages/Agola Color Schemes/AgolaDark.tmTheme"`
Or
Go to `Preferences > Color Schemes > Agola Color Schemes` and select `AgolaDark`...
