### ISSUE TITLE
JSON highlighting is very hard to see in Agola Dark

### ISSUE THREAD

**Issue by corysimmons** [UnderlineWords/Agola-Color-Schemes#2]
I love the theme. Is it okay if I offer suggestions here?

![image](https://cloud.githubusercontent.com/assets/224636/12957658/d154f536-cffb-11e5-923a-b92a8eabc793.png)

I'm not sure if this is because I'm colorblind, but I can barely see what I've highlighted. I'm happy to submit PRs for these types of little things if you're interested.

**Comment by UnderlineWords** [comment]
Yeah sure! Feel free to submit PR @corysimmons :)
:+1:

**Comment by corysimmons** [comment]
Alright, I'll try to PR as I go. It'll probably just be for the dark theme though. :+1:

**Comment by UnderlineWords** [comment]
Follow the updated.
https://github.com/UnderlineWords/Agola-Color-Schemes/releases/tag/1.4.0

**Comment by corysimmons** [comment]
Cool thanks! :+1: 

I started working on my own scheme and realized how difficult it is.

**Comment by UnderlineWords** [comment]
:+1: i can understand what you mean. I started at the same point. :)

**Comment by corysimmons** [comment]
Also, I think your theme is different on http://colorsublime.com/?q=agola

The one I screenshotted was the colorsublime one.

**Comment by UnderlineWords** [comment]
Hmm, this is old version and even maybe first release. I should submit a new PR for Colorsublime. 
Thank you for the notice :+1:

**Comment by corysimmons** [comment]
np :+1:
